#╔══════════════════════════════════════════════╗
#║            Длина строки кода (E501)          ║
#╚══════════════════════════════════════════════╝
line-length = 120

#╔══════════════════════════════════════════════╗
#║            Целевая версия python             ║
#╚══════════════════════════════════════════════╝
target-version = "py312"

#╔══════════════════════════════════════════════╗
#║                Типы проверок                 ║
#╚══════════════════════════════════════════════╝
lint.select = [
    "A", # Избегайте использования ключевых слов, которые перекрывают встроенные функции Python
    "B", # Предупреждения о безопасности
    "C90", # complex structure
    "E", # Стиль кода согласно pycodestyle
    "W", # warnings
    "F", # Статический анализ кода с помощью pyflakes
    "ISC", # Неявная конкатенация строк
    "UP", # Предупреждение о доступных лучших синтаксических возможностях в вашей версии Python
    "RUF", # Собственные правила разработчика
    "ANN", # type annotation
    "I", # imports
    "N", # pep8 naming
    "ASYNC",
    "S",
    "PIE",
    "PYI",
    "PT",
    "Q",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "ARG",
    "PTH",
    "TD",
    "FIX",
    "ERA",
    "PGH",
    "FLY",
    "PERF"
]

#╔══════════════════════════════════════════════╗
#║          Игнорирование типа ошибки           ║
#╚══════════════════════════════════════════════╝
lint.ignore = [
    "F811", # Переопределение и неиспользование
    "RUF001", # Кириллические символы в string
    "RUF002", # Кириллические символы в dockstring
    "RUF003", # Кириллические символы в комментарии
    "A003", # Использование ключевых слов, которые перекрывают встроенные функции Python
    "ISC002", # Неявно объединенные строковые литералы в нескольких строках
    "ANN101",
    "ANN102",
    "PYI041"
]

#╔══════════════════════════════════════════════╗
#║         Исключение файла из проверки         ║
#╚══════════════════════════════════════════════╝
exclude = [

]

#╔═══════════════════════════════════════════════════╗
#║   Автоматическое исправление при запуске линтера  ║
#╚═══════════════════════════════════════════════════╝
fix = false  # По умолчанию - выключено (включайте если уверены)

lint.fixable = [# По умолчанию - "ALL" (все правила считаются исправимыми)
    "ALL"
]

lint.unfixable = [# По умолчанию - [] (Ни одно правило не проигнорировано)

]

#╔═══════════════════════════════════════════════════╗
#║ Игнорирование указанным файлом - указанной ошибки ║
#╚═══════════════════════════════════════════════════╝
[lint.extend-per-file-ignores]

